name: NajranGate
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  adobe_xd: ^0.1.3
  fluttertoast: ^3.1.3
  flutter_svg: ^0.17.4
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  firebase_database: ^3.0.4
  firebase_storage: ^3.0.3
  firebase_core: ^0.4.0+6
  toast: ^0.1.3
  flutter_spinkit: "^4.1.2"
  image_picker: ^0.6.7+11
  path_provider: ^1.6.11
  flutter_image_compress: ^0.6.8
  flutter_swiper: ^1.1.6
  url_launcher: ^5.4.10
  firebase_messaging: ^5.1.2
  fimber: ^0.4.0
  flutter_rating_bar: ^2.0.0
  smooth_star_rating: ^1.1.1
  google_sign_in:
  flutter_slidable: ^0.5.4
  auto_size_text: ^2.1.0
  flutter_local_notifications: ^1.4.4+1
  multi_image_picker: ^4.6.6
  http: ^0.12.2
  persian_number_utility: ^0.1.2
  image:
  esys_flutter_share: ^1.0.2
  rflutter_alert: ^1.1.0
#  firebase_in_app_messaging: ^0.1.1+3
#  firebase: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_lancher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/ic_lancher.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
     #- images/a_dot_burr.jpeg
     - assets/images/ic_confirmephone.png
     - assets/images/ic_ads.png
     - assets/images/antenna.png
     - assets/images/image_privcy_policy.png
     - assets/images/ic_background.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Estedad-Black
       fonts:
         - asset: assets/fonts/Estedad-Black.otf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
